<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Models\RaceModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Fonts\" />
    <Folder Include="wwwroot\DriverImages\" />
    <Folder Include="wwwroot\TeamImages\" />
  </ItemGroup>

</Project>
